### ISSUE TITLE
Click to Pause/Unpause not working?

### ISSUE THREAD

**Issue by johnjosephadams** [AjaxGb/Better-Chrome-Native-Video#17]
Hi,

I'm trying to use this extension with MLB TV's player, and it works for the various things I've tried, like the left and right arrow keys skipping back/forth etc. 

But when it comes to pausing I'm having an issue:

1. If I click to focus on the video, pressing spacebar DOES pause the video. (Which is good.)

2. But if I have it set so that just clicking the video should pause/unpause it, that doesn't do anything—no action occurs by just clicking. (I do have "click once to both focus and play" selected.)

Is that maybe just not compatible with this video player, and I'm out of luck, or is something not working correctly? 

-John

**Comment by AjaxGb** [comment]
This extension is really only designed to work with the plain vanilla Chrome video player, and by default will only activate on videos that are using the plain vanilla controls. Trying to interface correctly with *all* video players just isn't feasible.

I don't have an MLB TV subscription, so testing would be difficult, but I suspect that this extension isn't active on it at all. Arrow keys probably work because the MLB TV developers implemented them on their own. Try using the comma and period keys (`,` and `.`) to go back and forward by 1/60 of a second; most video players don't have that. If the comma and period keys do nothing, you'll know that this extension isn't active on the video.

**Comment by johnjosephadams** [comment]
Oh, you're totally right! It's not actually working at all.

Maybe MLB updated the player recently because I swear that before no
keyboard shortcuts were working with their player (no spacebar to pause
etc.)

John

**Comment by AjaxGb** [comment]
No problem! But yeah, this extension isn't going to be supporting non-vanilla players anytime soon.
