### ISSUE TITLE
Doesn't work on site channel9

### ISSUE THREAD

**Issue by JonasNo** [AjaxGb/Better-Chrome-Native-Video#5]
Example url: https://channel9.msdn.com/Events/CPP/CppCon-2016/CppCon-2016-Achieving-performance-in-financial-data-processing-through-compile-time-introspection?format=html5

**Comment by AjaxGb** [comment]
Pushing out a fix right now. The Chrome store should update within an hour.

**Comment by JonasNo** [comment]
Sorry for the delay. It got lost in the sea of notifications.
Did this fix work for you? On my end the keyboard shortcuts still don't work.

**Comment by AjaxGb** [comment]
Ah, I see what the issue is. One of my other plugins was blocking the website's custom player from loading, so clicking on it just took me straight to the video file itself. I apologize for my confusion.

That website is using a custom video player. This plugin is only designed to work with Chrome's built-in player, and is incompatible with most custom players.

Here's a workaround. Change the dropdown selector under "Download this episode" to "High", "Low", or "Mid Quality MP4". Right-click the "download video" button and choose "Open link in new tab". This will not download the video, but will open a new tab playing the video. You can now view the video using Chrome's native video player, with all the keyboard shortcuts you want.
