### ISSUE TITLE
Uncaught TypeError: 'observe' parameter 1 is not of type 'Node'

### ISSUE THREAD

**Issue by JonasNo** [AjaxGb/Better-Chrome-Native-Video#8]
chrome-extension://llhmaciggnibnbdokidmbilklceaobae/page.js:472
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.

URL:
`https://thevideo.me/embed-nizx5vly04pm-850x450.html`

**Comment by AjaxGb** [comment]
I've looked into this, and I've found the source of the error. It appears to be the advertisements on that page triggering a (minor) bug in Chrome.

Specifically, the ads are trying to fool ad blockers by loading an apparently innocent document, which immediately redirects to the real advertisement. Since the ads are now loading a different document, Chrome never finishes loading the original document. The bug is that any extensions that tried to run on the original document are still run, but are given a page that never finished loading. Mine is not the only extension that throws errors in this case.

The good news is that the errors can be safely ignored, since they are happening on documents that are being unloaded anyway. I could add a check for this bug and cancel loading the extension on bugged documents, but unless you really want me to I don't think it's necessary.

**Comment by JonasNo** [comment]
Okey. Thought I report it just in case.
Have the minor bug been reported to `crbug.com`?
I'm curious of how you figured out the problem. Can you explain the process, please?

**Comment by AjaxGb** [comment]
It does not appear to have been reported yet, and I haven't done so myself.

As for my process, a rough description is:
* "Parameter 1" is not a node? Parameter 1 is `document.body`. If it's not a node, then what is it?
* `null`. That's odd, every loaded document should have a body, and the way I set up my extension guarantees that Chrome will load all DOM before my content script is run.
* Let's open up the Developer Console and set it to pause on every exception. Ah, I can see that at this moment the frame in question does indeed have no body, and the only thing in the head is a line of JS to redirect it. Is that the problem?
* After some testing, and making a test document to see if I could reproduce the problem, yes, that's it.

**Comment by AjaxGb** [comment]
Reported: https://bugs.chromium.org/p/chromium/issues/detail?id=733288
